### ISSUE TITLE
Time for alarm changes under certain conditions

### ISSUE THREAD

**Issue by thakyZ** [Stefangansevles/RemindMe#176]
**Describe the bug**
I have noticed that some of my alarms have had the time that they are supposed to go off at, change depending on how late after they start going off that I dismiss them.   
Though I would like to note, I am not 100% sure that this is the case, however I have all my alarms at 30 min intervals and over time of use of this application they'll become some other time such as 12:41 for example.   
I did have at one point all my alarms that were supposed to go off between 11:00 AM and 1:00 PM end up having the same time set for some reason.

**To Reproduce**
1. Set an alarm for any nearby time.
2. Have the alarm go off and wait about 15 mins for good measure
3. Dismiss the alarm
4. Check the alarm for if it's still the same time you had initially set.

**Expected behavior**
The alarm timestamp should not change whatsoever.

**Screenshots**
This is how the alarms should look
![Screenshot of how the alarms should look](https://user-images.githubusercontent.com/950594/228015642-c1c95555-3bd1-4b7e-be50-b4c1b86e42dd.png)

This is how the alarms end up looking like over time
![Screenshot of how the alarms end up looking like over time](https://user-images.githubusercontent.com/950594/228015380-06284204-5e57-4206-83db-88f220e63ad4.png)

**Please complete the following information**
 - Version 3.1.20

**Additional context**
As I stated earlier, I am not sure if the issue stems from dismissing the alarm later or not, but it just keeps happening.

**Comment by Stefangansevles** [comment]
Hi thakyZ,

The default behaviour is as follows:

You've set a reminder with an interval of every 15 minutes. The next occurance is 15:00. You dismiss the reminder at 15:02. Instead of the next reminder occurance being 15:17, it's 15:15. Initial date + interval.

If you would like to change this to instead be 15:17, you can check the following option:

![image](https://user-images.githubusercontent.com/25766371/229324712-a3839e18-ede8-449f-80c0-65121f2b4a7a.png)

Knowing this, does the issue still occur?

**Comment by thakyZ** [comment]
No it does not, very sorry only realized that after.
