### ISSUE TITLE
RemindMe\Properties\Settings.Designer.cs' could not be found.

### ISSUE THREAD

**Issue by majddhainy** [Stefangansevles/RemindMe#2]
After downloading the required libraries and trying to run the project, I get this error:

RemindMeApp\RemindMe\Properties\Settings.Designer.cs' could not be found.

Also:

RemindMeApp\Data Access Layer\bin\Release\Data Access Layer.dll' could not be found	Business Logic Layer

and

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\System.Data.SQLite.Core.1.0.109.1\build\net45\System.Data.SQLite.Core.targets.

Any help?

**Comment by Stefangansevles** [comment]
I initially (years ago) put all the files on github so people could clone the project and run and change it, but the more i added the harder that became, first the bunifu dll, then the online database ( i don't have files that have the pw included on github)

the .dll can not be found should be fixable by building the class library and thereby creating a dll

and for the nuget packages, you should be able to download them through visual studio if theyre missing? 

Unfortunately you're going to have to comment out/remove the sql database code in order to get rid of those error messages. 

all in all it should still be able to run after some refactoring

**Comment by Stefangansevles** [comment]
@majddhainy fixed this in the latest commit
